# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen_producto',
            name='id_imagen',
        ),
        migrations.RemoveField(
            model_name='ofertas',
            name='id_oferta',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='id_rol',
        ),
        migrations.RemoveField(
            model_name='tipos_productos',
            name='id_tipo',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_question',
        ),
    ]
