# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agroweb', '0002_auto_20160806_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.IntegerField()),
                ('estado', models.CharField(max_length=200)),
                ('direccion_envio', models.CharField(max_length=200)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroweb.Carrito_Compra')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('informacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=100)),
                ('contenido_noticia', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas_Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pregunta', models.IntegerField()),
                ('pregunta', models.CharField(max_length=100)),
                ('respuesta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='imagen_producto',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='id_oferta',
            new_name='oferta',
        ),
        migrations.RenameField(
            model_name='productos',
            old_name='id_tipo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_rol',
            new_name='rol',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='usuario_destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_destinatario_solicitudes', to='agroweb.Usuarios'),
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='usuario_remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_remitente_solicitudes', to='agroweb.Usuarios'),
        ),
        migrations.AddField(
            model_name='preguntas_productos',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroweb.Productos'),
        ),
        migrations.AddField(
            model_name='preguntas_productos',
            name='usuario_destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_destinatario_preguntas_productos', to='agroweb.Usuarios'),
        ),
        migrations.AddField(
            model_name='preguntas_productos',
            name='usuario_remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_remitente_preguntas_productos', to='agroweb.Usuarios'),
        ),
        migrations.AddField(
            model_name='noticias',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroweb.Usuarios'),
        ),
        migrations.AddField(
            model_name='factura',
            name='transportador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroweb.Usuarios'),
        ),
        migrations.AddField(
            model_name='chat',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroweb.Solicitudes'),
        ),
        migrations.AddField(
            model_name='carrito_compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroweb.Productos'),
        ),
        migrations.AddField(
            model_name='carrito_compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agroweb.Usuarios'),
        ),
    ]
