# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agroweb', '0003_auto_20160810_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntas_productos',
            old_name='id_producto',
            new_name='producto',
        ),
        migrations.RemoveField(
            model_name='preguntas_productos',
            name='id_pregunta',
        ),
    ]
