# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroweb', '0004_auto_20160810_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='productosFK',
            field=models.ManyToManyField(to='agroweb.Productos'),
        ),
        migrations.AddField(
            model_name='factura',
            name='transportadorFK',
            field=models.ManyToManyField(related_name='transportador_mxm', to='agroweb.Usuarios'),
        ),
        migrations.AddField(
            model_name='productos',
            name='usuarioFK',
            field=models.ManyToManyField(to='agroweb.Usuarios'),
        ),
    ]
